DROP TABLE IF EXISTS TN_AVATAR;

CREATE TABLE TN_AVATAR
(
  ID INT PRIMARY KEY,
  LEVEL INT
)

DROP TABLE IF EXISTS TN_JETPACK;

CREATE TABLE TN_JETPACK
(
  ID INT PRIMARY KEY,
  LEVEL INT
)

DROP TABLE IF EXISTS TN_USER;

CREATE TABLE TN_USER
(
  ID INT PRIMARY KEY,
  NAME VARCHAR,
  DISTANCE INT,
  AVATAR_ID INT REFERENCES TN_AVATAR(ID),
  JETPACK_ID INT REFERENCES TN_JETPACK(ID)
)

DROP TABLE IF EXISTS TN_RATING;

CREATE TABLE TN_RATING
(
  ID INT PRIMARY KEY,
  POSITION INT,
  USER_ID INT REFERENCES TN_USER(ID)
)